services:
  pizza-shop-web:
    build:
      context: ./pizza-shop-web
    ports:
      - "5173:5173"
    volumes:
      - ./pizza-shop-web:/app
    command: pnpm run dev -- --host 0.0.0.0

  pizza-shop-api:
    build:
      context: ./pizza-shop-api
    ports:
      - "3333:3333"
    volumes:
      - ./pizza-shop-api:/app
    command: bun run dev -- --host 0.0.0.0

  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: pizza_shop
    volumes:
      - postgres_data:/bitnami/postgresql

volumes:
  postgres_data:
